//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category_to_shop
    {
        public int codeCTS { get; set; }
        public int codeShop { get; set; }
        public int codeCategory { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
