//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shop()
        {
            this.Category_to_shop = new HashSet<Category_to_shop>();
            this.Searches = new HashSet<Search>();
        }
    
        public int codeShop { get; set; }
        public string nameShop { get; set; }
        public string passwordShop { get; set; }
        public string phoneShop { get; set; }
        public string mailShop { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public string fromHour { get; set; }
        public string toHour { get; set; }
        public string addressString { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category_to_shop> Category_to_shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Search> Searches { get; set; }
    }
}
